### ISSUE TITLE
Interest in moving go/bazel/bazel.go into rules_go

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_webtesting#108]
I was looking through your code and niticed [this utility](https://github.com/bazelbuild/rules_webtesting/blob/master/go/bazel/bazel.go). I am interested in having access to this in my own code. That made me think it might be useful to upstream into the rules_go repo.

@jayconrod, I would also be interested in your thoughts on this.

**Comment by jayconrod** [comment]
Seems fine to me, though if it's in rules_go, it shouldn't mention `io_bazel_rules_webtesting` in `DefaultWorkspace`. The functions look quite useful for tests though.

[bazelbuild/rules_go/go/tools](https://github.com/bazelbuild/rules_go/tree/master/go/tools) would be a good place for this.

**Comment by DrMarcII** [comment]
Feel free.

@jayconrod why not just bazelbuild/rules_go/tools (what is the benefit of nesting in go?)?

**Comment by jayconrod** [comment]
@DrMarcII Consistency, basically. We already have a go/tools directory containing other tools for build, test, and maintenance.

**Comment by DrMarcII** [comment]
But those are conceptually different tools (in fact, I think most/all of those are binaries). This is a library for use in Bazel projects using go.

**Comment by joshbruning** [comment]
@achew22 - Should this be closed out or should this library be updated to reference bazelbuild/rules_go?
