### ISSUE TITLE
dart_web_test_suite fails on Mac

### ISSUE THREAD

**Issue by staats-google** [bazelbuild/rules_webtesting#112]
Running the WebDriver tests from: https://github.com/google/webdriver.dart

The dart_vm_test targets work fine, the generation works fine, but the dart_web_test_suites seem to die around Go:

```
staats-macbookair:webdriver.dart staats$ bazel test test:alert_test_io
Extracting Bazel installation...
...........
ERROR: /private/var/tmp/_bazel_staats/a5854b8c51697a7bcf462b387687c967/external/io_bazel_rules_go/go/toolchain/BUILD:10:1: no such package '@io_bazel_rules_go_toolchain//': Not a file: /private/var/tmp/_bazel_staats/a5854b8c51697a7bcf462b387687c967/external/golang_darwin_amd64/BUILD and referenced by '@io_bazel_rules_go//go/toolchain:go_tool'.
ERROR: Analysis of target '//test:alert_test_io_chromium-native' failed; build aborted.
INFO: Elapsed time: 35.289s
ERROR: Couldn't start the build. Unable to run tests.
```

This might be ultimately a Go issue, but also a problem for anyone working on Mac.

**Comment by joshbruning** [comment]
staats-google - I believe this issue is now obsolete; can we close it out?

**Comment by staats-google** [comment]
Yep, can die. Until Dart's bazel rules can play nice with the larger bazel
world this is a non-issue.

-- Matt
