### ISSUE TITLE
ci.bazel.io build red

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_webtesting#151]
Hello :)

ci.bazel.io build of rules_webtesting is red since today, looks like some go dependency went rogue. Please please help? :)

Details:
http://ci.bazel.io/view/Dashboard/job/rules_web/604/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console

Thanks a lot!

**Comment by joshbruning** [comment]
I suppose we'll have to revert this for now: https://github.com/bazelbuild/rules_webtesting/commit/12613b407a3324093e18712d632fe99ac4bd16ae

**Comment by joshbruning** [comment]
Just got into the office; attempting to fix forward: I repro'd and resolved the error locally.
