### ISSUE TITLE
rules_webtesting not working with bazel 0.4.5

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_webtesting#156]
I set up my workspace like the readme says and copied the sample python test. When I try to run it I get:

ERROR: error loading package '': Encountered error while reading extension file 'web/repositories.bzl': no such package '@io_bazel_rules_webtesting//web': Invalid branch, tag, or commit: Ref tags/HEAD can not be resolved.

**Comment by joshbruning** [comment]
Thanks for the report; I believe the example requires updating. I know we updated the rules_go version for example - it may need to be 0.5.0 now... Wouldn't be surprised if other updates are required. Fwiw: I use 0.5.2; possible that bazel 0.5.0 introduced some breaking change as well... I personally have very little bazel exp, but I think the primary maintainer should be back next week if no one has time to address this before then.

**Comment by ribrdb** [comment]
Thanks. I got it to work with
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.5.0",
)
and
git_repository(
    name = "io_bazel_rules_webtesting",
    remote = "https://github.com/bazelbuild/rules_webtesting.git",
    commit = "5fd06f193dc401c0480f748db7a7f01790dc3e70",
)

Also I had to add tags = ["noci"] to my test.
There were a couple other confusing things:
The .py file has to have the same name as the test
I have to use web_test_data instead of data option to py_web_test_suite

**Comment by DrMarcII** [comment]
I removed the requirement for the noci tags when using my defined browsers, and updated the documentation.
