### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_webtesting#178]
At least half the Angular ecosystem runs on Windows machines.

currently trying the simple python example from the README I get

```
ERROR: C:/users/angular/appdata/local/temp/_bazel_angular/zyn_1rhm/external/io_bazel_rules_webtesting/browsers/BUILD:67:
1: Configurable attribute "environment" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @io_bazel_rules_webtesting//browsers:linux
 @io_bazel_rules_webtesting//browsers:mac.
ERROR: Analysis of target '//:browser_test_chromium-native' failed; build aborted.
```

**Comment by joshbruning** [comment]
Native Windows support is currently scheduled for Q4, but we have a Windows machine on which to perform the work, and there are no blockers. Is resolution in October sufficient, or do you need something this month?

**Comment by alexeagle** [comment]
That's fine, I don't support Windows with the typescript rules yet either.

**Comment by joshbruning** [comment]
My PR will resolve many of the issues; a fix to https://github.com/bazelbuild/rules_go/issues/736 should resolve remaining known issues. (Then the ball will be back in our court.)

**Comment by filipesilva** [comment]
As far as I can tell, https://github.com/bazelbuild/rules_webtesting/pull/293 removed all Windows related configurations introduced in https://github.com/bazelbuild/rules_webtesting/pull/179. 

Are these expected to be re-introduced?

**Comment by alexeagle** [comment]
Even if users are required to define their own browser configurations, it still seems there is no such configuration that works with these rules on Windows.

**Comment by joshbruning** [comment]
A fix for https://github.com/bazelbuild/rules_go/issues/1619 was made about a month ago. We can try to update our version of rules_go and see what the next blocker is; Marc had only removed Windows configurations as they weren't working anyway.

**Comment by joshbruning** [comment]
After the most recent rules_go update, core Go components seem to build fine (!), but the browser configurations are getting stuck on web/internal/extract.sh - need to make this Windows compatible, I think (so long as I'm reading the errors correctly).

**Comment by filipesilva** [comment]
Heya just wanted to mention I tried the latest master and Chrome does run on Windows. Cheers!

**Comment by filipesilva** [comment]
There seems to be some issue with Chrome 88+ on Windows Server:

- https://stackoverflow.com/questions/51860091/does-chromium-headless-work-on-windows-server-core-2016
- https://bugs.chromium.org/p/chromium/issues/detail?id=873097

In our case the tests pass locally but not on our Windows CI: https://source.cloud.google.com/results/invocations/17e1620a-df58-430b-bbad-49dfbef6332e/targets/%2F%2Fexamples%2Ftesting:testing_chromium-local/log

**Comment by joshbruning** [comment]
(Chrome 88+ -> Chrome 68+)

We validated on "Windows Server 2016 Datacenter".

66.0.3359.181 has branch base position: 540276. 540270 is the closest I see in chromium-browser-snapshots. In web/repositories.bzl, you can put Chromium/Windows back on 540270 (and update sha).

You'll also probably want to put chromedriver/Windows back on 2.38:
https://chromedriver.storage.googleapis.com/2.38/chromedriver_win32.zip

If you send me a pull request, I'll merge it; otherwise, let me know if you just want me to do it when I have a spare cycle.

**Comment by filipesilva** [comment]
@joshbruning thanks for the guidance, I put a PR up at https://github.com/bazelbuild/rules_webtesting/pull/303
