### ISSUE TITLE
upgrading to HEAD fails Go builds that succeeded previously

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#217]
After updating to b944304cd5065fc7d9b695fd1051a3d0a3f65af3, my go tests now fail where they succeeded before on macOS. 

Using the chromium-local target in the browsers package, the process doesn't even seem to boot but my test code is still able to call things like FindElement. I'll try to get more debugging info, but nothing is returned from selenium's browser logs rpcs.

Using chrome-external, it immediately fails with `[External WebDriver Environment]: environment variable "EXTERNAL_WEBDRIVER_SERVER_ADDRESS" not set`. Going from the name (though it's not documented anywhere), it's maybe expected that there's another webdriver process running somewhere and the user is supposed to set that?

**Comment by jmhodges** [comment]
Agh, my way of getting more debug info depended on the chromedriver code that is no longer in there. Is there a way to get wsl to print more info about like chromedriver executable's `--verbose` flag?

**Comment by DrMarcII** [comment]
*-external is intended for use with an already running WebDriver endpoint (e.g. ChromeDriver, GeckoDriver), and the use of a --test_env=EXTERNAL_WEBDRIVER_SERVER_ADDRESS=<address of already running driver>.

To get more debugging info with the chrome-local, you can modifiy rules_webtesting/browsers/chromium-local.json to add "--verbose" the wsl:config->args (these are args that are passed to whatever endpoint binary WSL launches).

As for your comment about the process doesn't even seem to boot..., I am not sure what you mean. If you are talking about not seeing the browser, that is expected because I have changed my default browser configs to be headless (chromeOptions->args in rules_webtesting/browsers/chromium-local.json). This was so that I didn't have to worry about starting an XDisplay on my continuous builds (which is what these browser definitions are intended for).

**Comment by jmhodges** [comment]
Hm, I'm revisiting my attempted upgrade and so far I've gotten, without logging more, these error messages:

```
2018/04/12 08:09:43 Response: map[sessionId: status:0 value:map[build:map[version:alpha] os:map[arch:x86_64 name:Mac OS X version:10.13.4]]]
2018/04/12 08:09:43 Error creating W3C session: [Go WebDriver Client] (session not created) session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.4 x86_64)
2018/04/12 08:09:43 cmd has exited: signal: killed
Starting ChromeDriver 2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef) on port 58035
Only local connections are allowed.
2018/04/12 08:09:43 Response: map[sessionId: status:0 value:map[build:map[version:alpha] os:map[arch:x86_64 name:Mac OS X version:10.13.4]]]
2018/04/12 08:09:44 cmd has exited: signal: killed
```

The "missing or invalid capabilities" seems important. I commented out all of my capability munging[1] and that didn't seem to solve the problem. I'll try to get more verbose logging, but I'm not sure if that'll help.

[1] it was originally 

```
	caps := selenium.Capabilities{}
	caps.AddChrome(chrome.Capabilities{
	MobileEmulation: &chrome.MobileEmulation{
		DeviceMetrics: &chrome.DeviceMetrics{
			Width:  500,
			Height: 500,
		},
	},
	})
	caps.AddLogging(slog.Capabilities{
		slog.Browser: slog.All,
	})
	wd, err := webtest.NewWebDriverSession(caps)
```

**Comment by jmhodges** [comment]
Adding  `"--enable-logging=stderr", "--v=1"` to the args array in chromium-local.json doesn't seem to have added any more logging.

Did I screw up the formatting? It looks like `"args" : ["headless", "use-gl=swiftshader-webgl", "--enable-logging=stderr", "--v=1"],`

I'm still getting the same errors.

**Comment by jmhodges** [comment]
I also tried upgrading the go selenium library in rules_webtesting but that doesn't seem to have fixed it.

**Comment by jmhodges** [comment]
Booting the Chromium binary directly in not-headless mode does get a request for access to the "login" keychain to 'use your confidential information stored in "Chromium Safe Storage" in your keychain'.

**Comment by jmhodges** [comment]
The args definitely don't seem correct. Running `bazel-bin/external/io_bazel_rules_webtesting//third_party/chromium/chromium.out/Chromium.app/Contents/MacOS/Chromium headless use-gl=swiftshader-webgl` directly gets you a head-ful Chromium that's going to the site "headless". This seems like a bug?

**Comment by jmhodges** [comment]
Oh! A "--" gets added to all those flags. Now I can get Chromium to immediately exit when run with `--headless --use-gl=switshader-webgl`

And I got an interesting error:

```
$   bazel-bin/external/io_bazel_rules_webtesting//third_party/chromium/chromium.out/Chromium.app/Contents/MacOS/Chromium --headless 
[0413/134315.218063:ERROR:crash_report_database_mac.mm(95)] mkdir /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/execroot/founding/bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromium/chromium.out/Chromium.app/Contents/Versions/66.0.3356.0/Chromium Framework.framework/Versions/A/new: Permission denied (13)
[0413/134315.217681:ERROR:crash_report_database_mac.mm(95)] mkdir /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/execroot/founding/bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromium/chromium.out/Chromium.app/Contents/Versions/66.0.3356.0/Chromium Framework.framework/Versions/A/new: Permission denied (13)
```

**Comment by jmhodges** [comment]
Hunh, if I delete the "chromeOptions" from chromium-local entirely, the tests run successfully but not headless.

**Comment by jmhodges** [comment]
I can't find where chromeOptions is read. How they are handled?

**Comment by jmhodges** [comment]
Hm, deleting either the args or the binary entry isn't enough to get this to work, so it seems to be the chromeOptions itself.

**Comment by DrMarcII** [comment]
Chrome Options is read by chromedriver; nothing in the rules_webtesting code base does anything special with it.

Maybe OSX doesn't support --headless or doesn't support swiftshader-webgl. If you remove just those two options from args in chromeOptions, does it work?

**Comment by jmhodges** [comment]
Oh, the obvious thing to try. Yeah, looks like the chromedriver versions doesn't support headless on macOS

**Comment by jmhodges** [comment]
And, btw, that repro works on linux. See the travis build here: https://travis-ci.org/jmhodges/bazel_bugs/builds/366361838

(Also, adding `ignore-certificate-errors` to `args` wasn't the fix.)

**Comment by jmhodges** [comment]
Ah! It looks like something called "acceptInsecureCertificates" is now a thing as of chromediver 2.35! https://bugs.chromium.org/p/chromium/issues/detail?id=721739

For my Go code, I needed to add 

```
	caps := selenium.Capabilities{}
	caps["acceptInsecureCerts"] = true
```

That's similar to other langs. You can also add `allow-insecure-localhost` to the `args` in the rules_webtesting json for the rule.

**Comment by jmhodges** [comment]
(I do not understand why headless requires that while not running as headless does not, but writing software is a complicated endeavor.)
