### ISSUE TITLE
Consider renaming rules_web -> rules_webtesting

### ISSUE THREAD

**Issue by jart** [bazelbuild/rules_webtesting#22]
I was really confused when I first read this project. I thought it was going to be a one stop shop for web development. But according to the readme, this project seems to have a razor-sharp focus on having a positive impact on web testing. So maybe it would be better if this project was renamed rules_webtesting.

Thoughts @DrMarcII and @damienmg?

**Comment by DrMarcII** [comment]
I am fine with the name change.

**Comment by damienmg** [comment]
Renaming a repository just like that is a breaking change and should have wait for our green /cc @kchodorow

**Comment by damienmg** [comment]
(That is said, my personal opinion is that rules_webtesting is a more explicit name so better).
