### ISSUE TITLE
Split web_test_repositories() into per-language workspace rules.

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_webtesting#23]
To remove the rules_go dependency for a java-only project, consider splitting `web_test_repositories()` into `java_webtesting_repositories()` and `go_webtesting_repositories()`, loaded and called independently by the end-user.

**Comment by DrMarcII** [comment]
Web Test Launcher (the binary that actually manages all the servers required for web tests, and launches the actual test) is implemented in Go, so splitting the repositories rules would not remove the dep on rules_go.

**Comment by pcj** [comment]
Thx, clarified.
