### ISSUE TITLE
Need a release to support latest rules_go

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_webtesting#273]
`WORKSPACE`:
```
http_archive(
    name = "io_bazel_rules_webtesting",
    url = "https://github.com/bazelbuild/rules_webtesting/archive/v0.2.0.zip",
    strip_prefix = "rules_webtesting-0.2.0",
    sha256 = "cecc12f07e95740750a40d38e8b14b76fefa1551bef9332cb432d564d693723c",
)
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.13.0/rules_go-0.13.0.tar.gz",
    sha256 = "ba79c532ac400cefd1859cbc8a9829346aa69e3b99482cd5a54432092cbc3933",
)
```
causes
https://circleci.com/gh/alexeagle/angular-bazel-example/650
```
ERROR: /usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c0aaa094e7be03dbabccfd0d5d7e8a8/external/io_bazel_rules_webtesting/web/repositories.bzl:18:1: file '@io_bazel_rules_go//go:def.bzl' does not contain symbol 'go_repository'
```

https://github.com/bazelbuild/rules_go/blob/07ef9e307a8f0095e5b10a70e1d291eace65eb61/deprecation.rst#removed-features
says
Legacy go_repository and new_go_repository
Deprecated in: 0.12.0
Removed in: 0.13.0
The go_repository rule has moved from @io_bazel_rules_go to @bazel_gazelle. Gazelle is a core part of go_repository, and moving go_repository to that repository allows us to reduce rules_go's dependence on Gazelle.

**Comment by alexeagle** [comment]
oh, sorry, just need this commit
https://github.com/bazelbuild/rules_webtesting/commit/7726422cf6c9c7ff5542540bbb05d2381ca6f73a

so could you tag a release sometime? thanks!

**Comment by DrMarcII** [comment]
Done.
