### ISSUE TITLE
WORKSPACE example shouldn't point to master

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/rules_webtesting#279]
The README configuration section points to the master branch of the WORKSPACE dependencies.

It should point to known good releases, or tell how to update to a latest release. Otherwise problems like this issue can happen when a breaking change is submitted: https://github.com/bazelbuild/rules_typescript/issues/233

**Comment by DrMarcII** [comment]
The README section is very clear that you should only point to master for experimental/example usage, and that you should pick a specific release or commit when actually using it.

**Comment by kellycampbell** [comment]
OK, yup, I totally overlooked that comment. However, this is inconsistent with most of the other bazelbuild/rules_  projects READMEs. They specify a version and then also tell you to set the version to something more up-to-date if you want. I think using `master` is setting a bad example for those who are new to bazel.
