### ISSUE TITLE
Some repositories have no Windows version

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_webtesting#284]
On windows, the `rules_typescript` project fails to build:
```
$ bazel build //...

ERROR: C:/users/alexeagle/_bazel_alexeagle/hxhfuc3q/external/io_bazel_rules_webtesting/third_party/geckodriver/BUILD.bazel:25:1: no such package '@org_mozilla_geckodriver//file': ind
ex out of range (index is 0, but sequence has 0 elements) and referenced by '@io_bazel_rules_webtesting//third_party/geckodriver:geckodriver'                                         
ERROR: Analysis of target '//examples/protocol_buffers:test_firefox-local' failed; build aborted: Analysis failed                                                                     
```

Seems it's because https://github.com/bazelbuild/rules_webtesting/blob/c11e47ad49b90956b20c5b64ec1addea9a443096/web/repositories.bzl#L482-L499 is missing a windows case.

**Comment by alexeagle** [comment]
All users are expected to define their own browsers? That seems like an
onerous requirement - is it documented?

**Comment by DrMarcII** [comment]
The examples on the README.md very clearly state that using the existing browsers is only for experimental/prototyping purposes, and that they should define their own browsers for longer term usage.

We are not able to be in the business of determining which browsers and versions people should be using; it is up to the users to decide which ones matter to them and their products. We only define browsers in rules_webtesting to provide examples that users can follow when defining their own and to run the tests in rules_webtesting. That said, defining your own browsers is mostly a matter of copy/paste from this project followed by updating versions etc. as necessary.

**Comment by joshbruning** [comment]
All users of rules_webtesting are expected to get their browsers from outside of rules_webtesting. Whether or not bazelbuild (or some other Google entity) provides these is an open question. It is important that rules_webtesting updates be decoupled from browser updates to some extent. Users should have access to updated browser versions without requiring upgrade of rules_webtesting; rules_webtesting releases should not be tied to every browser vendor provider's release schedule - when a new Chrome stable is released, users should be able to easily use it immediately without having to wait for rules_webtesting release and following upgrade activities which may be required then.

There's also an open question of whether or not the current rules are the way which users should be referring to a browser - that is, from the Chromium repo, for example. It could be possible for rules_webtesting to provide Chrome, Firefox, etc. targets which use the locally available browser; then the local system, docker container, or whatever would be responsible for versioning (outside the invocations of bazel build/test).

**Comment by filipesilva** [comment]
@DrMarcII is there a good example somewhere of how users can define their own browsers? The readme states that one should create their own browser definitions but does not offer guidance on how that should be done.

**Comment by filipesilva** [comment]
Using the provided chromedriver, or trying to provide one myself using `web_test_archive` yields an error on windows:
```
ERROR: C:/users/kamik/_bazel_kamik/5c2rzegw/external/io_bazel_rules_webtesting/third_party/chromedriver/BUILD.bazel:28:1: Extracting ../org_chromium_chromedriver/file/chromedriver_win32.zip failed (Exit -1).
Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\users\kamik\_bazel_kamik\5c2rzegw\execroot\build_bazel_rules_typescript\external\io_bazel_rules_webtesting\web\internal\extract.sh" external/org_chromium_chromedriver/file/chromedriver_win32.zip bazel-out/x64_windows-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromedriver/chromedriver.out ""): %1 is not a valid Win32 application.
```
