### ISSUE TITLE
Headless chrome

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_webtesting#291]
Pls help me understand this better.

I would like to use headless chrome as a browser.  I see that the `chrome-local` browser definition passes the `--headless` flag.  So is this headless chrome already?   I believe not, since I'm getting annoying macos system dialogs when initializing a test case.

Therefore, how would I go about defining a new browser definition for headless chrome?  The metadata json file format is a bit opaque.

Thanks!

**Comment by DrMarcII** [comment]
chrome-local should be headless, but I haven't tried it on MacOS recently. I will look into this later today, or tomorrow (I don't have a MacOS machine handy at the moment).

**Comment by pcj** [comment]
OK thanks.  I believe you are right that it is the headless version.  If you have insight into why it prompts a system dialog on macos that would be welcome.  I'll go ahead and close this.
