### ISSUE TITLE
README example is busted

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#307]
When I add 

```
git_repository(
    name = "io_bazel_rules_webtesting",
    remote = "https://github.com/bazelbuild/rules_webtesting.git",
    commit = "7e730b14fb5d2537ede28675eadad1e184c2f717", # current master
)

load("@io_bazel_rules_webtesting//web:repositories.bzl", "web_test_repositories")
load("//web/internal:platform_http_file.bzl", "platform_http_file")
```

to my WORKSPACE, and try to build, I get this error:

```
$  bazel build //go/svc/fe:dev
ERROR: error loading package '': Extension file not found. Unable to load package for '//web/internal:platform_http_file.bzl': BUILD file not found on package path
ERROR: error loading package '': Extension file not found. Unable to load package for '//web/internal:platform_http_file.bzl': BUILD file not found on package path
```

I'm not sure what the fix is here. I've tried a few different commits and they all fail with the same error.

This is with bazel 0.18 on macOS.

**Comment by jmhodges** [comment]
Ah, the default visibility in that BUILD.bazel seems to not be public? 

So, I also tried adding "browser_repositories" to my other load statement with an arg asking for it to set up chromium for me with `browser_repositories(chromium=True)`.

But Chromium seems to be crashing whole cloth[1] once it gets to the logout part of all of my tests, so maybe that's not actually the supported way to get a browser going?

What's the right way?

[1] From my go test logs:
```
2018/11/03 21:40:16 "GET /assets/js/fakestripe.js HTTP/1.1" 200 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/68.0.3440.0 Safari/537.36"
 2018/11/03 21:40:21.744522 /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/sandbox/darwin-sandbox/1/execroot/founding/bazel-out/darwin-fastbuild/bin/go/svc/howsmyssl-billing/integration_test_chromium-local.runfiles/io_bazel_rules_webtesting/third_party/chromedriver/chromedriver.out/chromedriver has exited: <nil>
2018/11/03 21:40:24.733644 Error shutting down driver: os: process already finished
```

**Comment by DrMarcII** [comment]
The actual problem is that I forgot to include @io_bazel_rules_webtesting at the beginning of the load. I have updated the README.

As for the crashing problem, I don't know why that is happening. Using browser_repositories should work (although I don't recommend it as it means you are tied to whatever version of Chromium rules_webtesting in using). Without having the actual test code to play with myself, there is not much I can do to help you.

**Comment by jmhodges** [comment]
Yeah that was it.

For the crash, is there some easy way to get chromedriver to start logging somewhere? I tried with custom_browser and a patching .json with a "--log-path=welp.log" in the "google:wslConfig"->"args" section but that didn't take.

**Comment by jmhodges** [comment]
(Using chrome-external lets the tests pass, but I need to use chromium-local in CI)

**Comment by jmhodges** [comment]
I'm going to close this since the primary problem is handled
