### ISSUE TITLE
web_test_archive doesn't work outside of rules_webtesting repo

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#310]
web_test_archive, the wrapper func, is defined with references to `"//common/conditions:windows"` which will error with `no such package 'common/conditions'` when used in another repo.

I had already copied over the `//common/conditions` targets into my own repo used them in my `web_test_archive` calls for chromedriver and chromium, but `web_test_archive` hardcodes that last windows one in its wrapper for the `extract_exe` parameters it passes in. Can't get those to stop being called.

For context, I'm using `web_test_archive` because there's no way to use `custom_browser` to remove things from array arguments in the JSON which led me to trying `browser`. But using `browser` for a chromium browser requires a dependency on `//third_party/chromedriver` and `//third_party/chromium` and those are not public. Attempting to recreate those targets locally led to trying `web_test_archive`.

**Comment by jmhodges** [comment]
Example code:

```
browser(
    name = "chromium-logging-local",
    metadata = "chromium-logging-local-head.json",
    deps = [
        "@io_bazel_rules_webtesting//go/wsl",
        ":chromedriver",
        ":chromium",
    ],
)

config_setting(
    name = "mac",
    values = {"cpu": "darwin"},
)

config_setting(
    name = "linux",
    values = {"cpu": "k8"},
)

config_setting(
    name = "windows",
    values = {"cpu": "x64_windows"},
)

web_test_archive(
    name = "chromedriver",
    archive = "@org_chromium_chromedriver//file",
    extract = "build",
    named_files = select({
        ":windows": {
            "CHROMEDRIVER": "chromedriver.exe",
        },
        "//conditions:default": {
            "CHROMEDRIVER": "chromedriver",
        },
    }),
    visibility = ["//browsers:__subpackages__"],
)

web_test_archive(
    name = "chromium",
    archive = "@org_chromium_chromium//file",
    extract = "build",
    named_files = select({
        ":linux": {
            "CHROMIUM": "chrome-linux/chrome",
        },
        ":mac": {
            "CHROMIUM": "chrome-mac/Chromium.app/Contents/MacOS/chromium",
        },
        ":windows": {
            "CHROMIUM": "chrome-win32/chrome.exe",
        },
    }),
    visibility = ["//browsers:__subpackages__"],
)
```

**Comment by DrMarcII** [comment]
web_test_archive should be fixed now.
