### ISSUE TITLE
libX11.so.6 is dynamically linked

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_webtesting#322]
I am getting

20:36:13.640:ERROR [launcher]: Cannot start ChromeHeadless
	/Users/chlove/.cache/bazel/_bazel_chlove/d2cf91f570d86c1699adc2085f7e4aeb/sandbox/processwrapper-sandbox/3/execroot/gke_bazel_example/bazel-out/k8-fastbuild/bin/js-client/src/hello-world/test_chromium-local.runfiles/io_bazel_rules_webtesting/third_party/chromium/chromium.out/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

While running this inside a container. Looks like chrome install is not quite huermetic. Ideas?

**Comment by DrMarcII** [comment]
I am installing a standard release of Chromium; it is not definitely not hermetic. Unfortunately there is no good way to make it hermetic, it is up to you to make sure that your container includes the necessary dependencies.
