### ISSUE TITLE
README's WORKSPACE example is wrong

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#345]
The url provided in the README in the http_archive doesn't have the right formatting for where the assets would be for a version and also forgets to the quotation marks around it.

**Comment by jmhodges** [comment]
Also, the readme has

```
load("@io_bazel_rules_webtesting//web:repositories.bzl", "web_test_repositories")
```

in it but that line errors for me in 0.3.1:

```
ERROR: error loading package '': Every .bzl file must have a corresponding package, but '@io_bazel_rules_webtesting//web:repositories.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

**Comment by jmhodges** [comment]
Looks like that last issue was because the releases need a `stripe_prefix` call, like so:

```
rules_webtesting_vers = "0.3.1"
http_archive(
    name = "io_bazel_rules_webtesting",
    sha256 = "d71b9dc5fef03cc0c0974305b1c9a3c36f4df1b52ed3d5898f8fa4c5d9d4edb1",
    strip_prefix = "rules_webtesting-{v}".format(v = rules_webtesting_vers),

    urls = [
        "https://github.com/bazelbuild/rules_webtesting/archive/{v}.tar.gz".format(v = rules_webtesting_vers),
    ],
)
```

Another bug that cropped up is that the `browser_repositories` example call says there's a parameter `chrome` when there is not. There is a `chromium`, however.

But now for some reason, 0.3.1 thinks I need rules_scala even though I don't have any scala code no do I import it. I'm not sure how to get around this.

```
ERROR: error loading package '@io_bazel_rules_webtesting//scalatests/com/google/testing/web': in /private/var/tmp/_bazel_jeffhodges/15689f02a249bfc2939281a01a900f0c/external/io_bazel_rules_webtesting/web/scala.bzl: Unable to find package for @io_bazel_rules_scala//scala:scala.bzl: The repository '@io_bazel_rules_scala' could not be resolved.
```

**Comment by jmhodges** [comment]
Yeah, that rules_scala error is happening even on HEAD with the `browsers-0.3.2.bzl` load statement.

**Comment by DrMarcII** [comment]
Starting with 0.3.0 I recommend that users pull an archive with prebuilt binaries and fewer dependencies (including rules_scala). Unfortunately I forgot to upload the archive for 0.3.1. This is now fixed.

I have added the missing "s to the examples and changed chrome to chromium. Otherwise, AFAICT, the examples are now correct.

**Comment by jmhodges** [comment]
Thank you! That's fixed my issues
