### ISSUE TITLE
incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_webtesting#347]
This repository doesn't build with the Bazel flag `--incompatible_depset_is_not_iterable`:

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/107#bdba27ec-e1a4-4715-a36b-3edcfe3dc938

`bazel build //... --incompatible_depset_is_not_iterable`

Can you please take a look?

**Comment by DrMarcII** [comment]
I just tried this on master@head using Bazel version 0.25.2 on Linux and got no errors. From the logs on buildkite I can't see what version was checked out, but indicated problematic line with fixed at commit 3b237d1aa57d9bd10e6289f8caeee835fad1a841
