### ISSUE TITLE
incompatible_disable_deprecated_attr_params

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_webtesting#351]
According to Bazel CI, rules_webstesting doesn't work with Bazel flag `--incompatible_disable_deprecated_attr_params`:

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/110#f5e4c0cc-36b5-44b2-80fe-9b3ead98c239

I think you need to update your dependency on protobuf.
We plan to flip the flags soon.

**Comment by DrMarcII** [comment]
This error doesn't recreate for me locally.
