### ISSUE TITLE
Run against a binary

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_webtesting#362]
I have a web server binary defined as a `java_binary`. Is it possible to specify a binary to run and then point webdriver to it? E.g.

- Run web test suite
- Test suite starts web server
- Web driver is passed location of the sever, e.g. `locahost:5432`
- Web driver tests run against the server
- Web server is stopped

**Comment by DrMarcII** [comment]
We have no specific support for starting the environment that you are testing against in this project (and no plans to add it, as my experience in Google shows that there are too many ways to do this, and people are very opinionated about which is the best).

The simplest approach is include the binary as a data dep to the test rule, then use whatever exec libraries you have in the language you are writing your test in to launch that binary. You can find the path to the binary by using logic similar to https://github.com/bazelbuild/rules_webtesting/blob/master/go/bazel/bazel.go#L36.
