### ISSUE TITLE
document local parameter

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#384]
There's no documentation in the docstring for `wrap_web_test_suite`'s `local` parameter. (I'm also not exactly sure what it does. I wasn't able to find other docs on it)

It'd be cool if that param was documented!

**Comment by joshbruning** [comment]
local keyword precludes the action or test from being remotely cached, remotely executed, or run inside the sandbox. For genrules and tests, marking the rule with the local = True attribute has the same effect.

https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags

Perhaps we should add more links to bazel doc.

**Comment by joshbruning** [comment]
Also, link to the parameter: https://docs.bazel.build/versions/master/be/common-definitions.html#test.local
