### ISSUE TITLE
Are web/versioned/browsers-*.bzl files supposed to change?

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/rules_webtesting#386]
According to the readme:
> You can use the predefined browsers in @io_bazel_rules_webtesting//browsers by adding (note we keep versioned browser definitions here, so users can separate updating browser versions from updating the version of rules_webtesting they use):

However `web/versioned/browsers-0.3.2.bzl` was changed in https://github.com/bazelbuild/rules_webtesting/pull/368. Is that intentional (possibly because the version wasn't released)? If so, the wording in the readme should be made clearer.

**Comment by DrMarcII** [comment]
Until a version is released, the corresponding versions/browser-0.3.2.bzl file can change. I will update the readme.
