### ISSUE TITLE
Update chromium version

### ISSUE THREAD

**Issue by Serginho** [bazelbuild/rules_webtesting#422]
The last chromium version is 91, but bazel still uses 76

https://github.com/bazelbuild/rules_webtesting/blob/34c659ab3e78f41ebe6453bee6201a69aef90f56/web/versioned/browsers-0.3.2.bzl#L66

I'm getting some browser crashes in my web tests using Chrome 76. It would be nice if you update it.

**Comment by mtrea** [comment]
Thanks for the report - I'm planning to look into this today.
