### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break rules_webtesting in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_webtesting#449]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_webtesting. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-559d-4c89-8ad3-cff7b384e8f0)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-559a-44ea-acec-5a406cf4f14a)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-55a0-452f-a241-db634eb2b37c)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi Team, Gentle ping , Can you share any significant update on this issue. Thanks!

**Comment by mtrea** [comment]
Created https://github.com/bazelbuild/rules_webtesting/pull/470. Is it really just a trivial string replacement or was there something that required domain-specific knowledge here?

**Comment by mtrea** [comment]
Seems to be fixed, let me know if I've missed something.
