### ISSUE TITLE
Add support for C++

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/rules_webtesting#466]
https://github.com/GermanAizek/webdriverxx has a nice C++ API to put together requests for Selenium:

```cpp
#include "webdriverxx.h"

using namespace webdriverxx;

int main()
{
  FirefoxOptions opts;
  WebDriver browser = Start(Firefox());
  browser.Navigate("https://duckduckgo.org");
  Element elem = browser.FindElement(ByCss("input[name=q]"));
  elem.SendKeys("sha512 helloworld");
  elem.Submit();
  getchar();

  return 0;
}
```

would be nice if there would be a "binding" for C++?

How hard is it to add a rule that works like this?

```cpp
cpp_web_test_suite(
    name = "browser_test",
    srcs = ["browser_test.cpp"],
    browsers = [
        "@io_bazel_rules_webtesting//browsers:chromium-local",
    ],
    local = True,
    deps = ["@io_bazel_rules_webtesting//testing/web"],
)
```

**Comment by prachin77** [comment]
would you pls assign me this issue @Vertexwahn

**Comment by Vertexwahn** [comment]
@prachin77 I do not have the right to assign an item to someone in this repository. If you start to work on this issue a short notice here (and maybe a link to your PR) should be sufficient

**Comment by mtrea** [comment]
Raising this to the team to discuss

**Comment by mtrea** [comment]
Hi, I talked it over and we'd prefer to not have C++ support added. You're welcome to fork this and add it to the fork, but we're not in a position to be supporting/maintaining this. Sorry, I know this isn't the answer you were looking for.

**Comment by prachin77** [comment]
it's totally ok @mtrea . my intention was to have a exposure of open source contribution and to understand the flow of how it works . 
i'm also looking for a internship in a company pls help me get it or it will be very supportive from you if you'll help me get an interview with someone .
i'm havin knowledge in my realms .
