### ISSUE TITLE
rules_webtesting is broken with 403 Forbidden for download

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_webtesting#53]
Please consider mirroring the download on GCS to avoid those.

/cc @jart @DrMarcII

**Comment by damienmg** [comment]
Sorry forgot the link of the breakage http://ci.bazel.io/job/rules_web/157/

**Comment by DrMarcII** [comment]
@damienmg Since I renamed the project (which I did hastily and without verifying that it wouldn't cause problems), I haven't been able to get the Bazel CI build to run on pull requests. Can you help me fix this?
