### ISSUE TITLE
Please help me update the webtesting rules

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_webtesting#94]
I'm attempting to get a large change in to reorganize Bazel's execution root (see https://github.com/bazelbuild/bazel/issues/1681 for more details).  Basically, instead of external repositories being children of the main repository (`execroot/main_repo/external/remote_repo`) they are all siblings (`execroot/remote_repo` and `execroot/main_repo`). 

I'd like to get all of the projects that depend on the old behavior to be forward and backward compatible before I submit the change.  However, I'm having trouble getting the webtesting tests to pass, in particular, `//dart:webtest_test_chromium-native` fails with:

```
2017/02/01 18:01:41 launching server at: localhost:54587
Unhandled exception:
Could not import "package:test/test.dart" from "file:///home/kchodorow/.cache/bazel/_bazel_kchodorow/2f53ce1e4fad28a08e1bb04034180ff8/execroot/rules_web/bazel-out/local-fastbuild/bin/dart/webtest_test_chromium-native.runfiles/io_bazel_rules_webtesting/dart/test/webtest_test.dart": FileSystemException: Cannot open file, path = '/home/kchodorow/.cache/bazel/_bazel_kchodorow/2f53ce1e4fad28a08e1bb04034180ff8/execroot/rules_web/bazel-out/local-fastbuild/bin/dart/webtest_test_chromium-native.runfiles/io_bazel_rules_webtesting/lib/test.dart' (OS Error: No such file or directory, errno = 2)
null
2017/02/01 18:01:41 test failed exit status 255
```

I've been trying to debug this, but I am not familiar with dart and not sure how to fix.  It seems like an import path issue, but I'm not sure how to change it.  I think it should be looking in `webtest_test_chromium-native.runfiles/org_dartlang_pub_test/lib/test.dart` for this dart file, but I don't understand how to make it do so.

If you'd like to try it out, you'll need a version of Bazel with my execroot change: https://github.com/kchodorow/bazel/tree/execroot (`bazel build //src:bazel`) and update the version of the go rules rules_webtesting is using (feel free to use my fork: https://github.com/kchodorow/rules_webtesting).

This is the last issue I know of blocking the rollout of https://github.com/bazelbuild/bazel/issues/1681, so any help would be appreciated!

**Comment by DrMarcII** [comment]
This appears to be a problem with https://github.com/dart-lang/rules_dart, which are not considered production ready and which I am using in a fashion that they don't currently support. 

I have some idea as to what might be happening (I have run into and fixed similar problems twice before), and will try to fix it. But you should not consider this a blocker for your change to bazel.  That test should not be running on ci (both because of potential problems like this and because it doesn't work on Mac OS).

**Comment by kchodorow** [comment]
Great, thank you!  Let me know if I can help at all with fixing them.

**Comment by DrMarcII** [comment]
I get the following error when trying to compile bazel:

ERROR: /usr/local/google/home/fisherii/github/bazel/src/tools/android/java/com/google/devtools/build/android/proto/BUILD:10:1: Generating Java (Immutable) proto_library //src/tools/android/java/com/google/devtools/build/android/proto:serialize_format_proto failed: Process exited with status 1 [sandboxed].
Unknown flag: --direct_dependencies

I am using bazel 0.4.4.

**Comment by kchodorow** [comment]
Sigh, I've been working on this change so long my bazel repo wasn't compatible with 0.4.4.  I've updated it now (it was a force push, so you'll have to reclone or fetch -> reset --hard).

**Comment by DrMarcII** [comment]
I have sent dart-lang/rules_dart#90 that I think fixes the issue.

**Comment by kchodorow** [comment]
Great, thank you!

**Comment by DrMarcII** [comment]
The problems with rules_dart are more complex than I thought. I went ahead and disabled all of the dart stuff in here for now, and have files a  bug against rules_dart and someone over there is working on it.

Going to go ahead and close this out for now.
